---
micronaut:
  application:
    name: travel-assist
  server:
    port: 6566

kafka:
  bootstrap:
    servers: kafka:9092

listener:
  group-id: sabre-soap

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"


hibernate:
  hbm2ddl:
    auto: update

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  username: "${MYSQL_USER}"
  password: "${MYSQL_PASSWORD}"
  logSql: false
  dbCreate: update
  url: "jdbc:mysql://${JDBC_HOST}:3306/travel-assist?serverTimezone=EST5EDT"
  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED


travelful:
  cache:
    root: ./mnt/travelful/cache/